ccflags-y := -Wno-declaration-after-statement -Werror -std=gnu11
obj-$(CONFIG_BRIGHTSIGN_TETSUO_FPGA)	+= tetsuo.o
obj-$(CONFIG_BRIGHTSIGN_POE_LOAD) += brightsign-poe-load.o
obj-$(CONFIG_BRIGHTSIGN_GPIO_MUX) += brightsign-gpio-mux.o
obj-y += tiger-usb.o
obj-y += null-console.o
