obj-$(CONFIG_VIDEO_BS_TV) += bs-tv.o

EXTRA_CFLAGS += -Idrivers/media/video
EXTRA_CFLAGS += -Idrivers/media/tuners
EXTRA_CFLAGS += -Idrivers/media/dvb-core
EXTRA_CFLAGS += -Idrivers/media/dvb-frontends

